// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySAwxuTBX2vOuDG1DVVsZurkgNE5-fzA',
    appId: '1:311070860709:web:3a0513394f21ec533b744c',
    messagingSenderId: '311070860709',
    projectId: 'ditonton-d95bf',
    authDomain: 'ditonton-d95bf.firebaseapp.com',
    storageBucket: 'ditonton-d95bf.appspot.com',
    measurementId: 'G-LCJT2X5C4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJakx7S1P-5g3nZEzMpO4YCMAxjCKo8g',
    appId: '1:311070860709:android:eacd19d9b860ab2c3b744c',
    messagingSenderId: '311070860709',
    projectId: 'ditonton-d95bf',
    storageBucket: 'ditonton-d95bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgtpJOYjC7qngcNkRvozFJ_Xk3XUbZ4Y',
    appId: '1:311070860709:ios:f844e9b1373a8d573b744c',
    messagingSenderId: '311070860709',
    projectId: 'ditonton-d95bf',
    storageBucket: 'ditonton-d95bf.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
